# pre-commit config
#  used for repository consistency and local development
#  see repository readme for installation guide and usage

default_install_hook_types: [pre-commit, pre-push]
default_language_version:
  python: python3.13

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-json
      - id: debug-statements
      - id: end-of-file-fixer
      - id: detect-private-key
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: check-added-large-files

  - repo: https://github.com/python-poetry/poetry
    rev: 2.1.3
    hooks:
      - id: poetry-check
      - id: poetry-lock

  - repo: https://github.com/python-poetry/poetry-plugin-export
    rev: 1.9.0
    hooks:
      - id: poetry-export
        args: ["-o", "requirements.txt", "--without-hashes"]

  # - repo: https://github.com/astral-sh/ruff-pre-commit
  #   rev: v0.11.10
  #   hooks:
  #     - id: ruff
  #       args: [--fix]
  #     - id: ruff
  #       args: [--select, I, --fix]
  #     - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        files: src

  - repo: meta
    hooks:
      - id: check-useless-excludes
